### ISSUE TITLE
Error: Cannot find module 'debug'

### ISSUE THREAD

**Issue by 910JQK** [stkevintan/nw_musicbox#3]
[2686:0612/220811:ERROR:nw_shell.cc(335)] Error: Cannot find module 'debug'
    at Function.Module._resolveFilename (module.js:327:15)
    at Function.Module._load (module.js:264:25)
    at Module.require (module.js:356:17)
    at require (module.js:375:17)
    at Object.<anonymous> (/home/jqk/ProjectFiles/Remote/NetEaseMusic/node_modules/superagent/lib/node/index.js:6:13)
    at Module._compile (module.js:451:26)
    at Object.Module._extensions..js (module.js:469:10)
    at Module.load (module.js:346:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:356:17)
[2686:0612/220811:INFO:CONSOLE(329)] "Uncaught Error: Cannot find module 'debug'", source: module.js (329)
[2686:0612/220820:ERROR:nw_shell.cc(335)] TypeError: Cannot read property 'search' of undefined
    at <anonymous>:1:4
[2686:0612/220820:INFO:CONSOLE(1)] "Uncaught TypeError: Cannot read property 'search' of undefined", source:  (1)

**Comment by stkevintan** [comment]
尝试将node_module文件夹删除，然后在打开终端切换到项目文件夹，执行`npm i`试试。

**Comment by 910JQK** [comment]
[3882:0612/223438:INFO:CONSOLE(86)] ""an error called from getNetuser data not found or invalid! please login first!"", source: file:///home/jqk/ProjectFiles/Remote/NetEaseMusic/controller/category.js (86)
[3882:0612/223438:INFO:CONSOLE(129)] "", source: file:///home/jqk/ProjectFiles/Remote/NetEaseMusic/controller/category.js (129)
[3882:0612/223438:INFO:CONSOLE(129)] "", source: file:///home/jqk/ProjectFiles/Remote/NetEaseMusic/controller/category.js (129)
[3882:0612/223438:INFO:CONSOLE(129)] "", source: file:///home/jqk/ProjectFiles/Remote/NetEaseMusic/controller/category.js (129)
[3882:0612/223438:INFO:CONSOLE(129)] "", source: file:///home/jqk/ProjectFiles/Remote/NetEaseMusic/controller/category.js (129)
[3882:0612/223438:INFO:CONSOLE(129)] "", source: file:///home/jqk/ProjectFiles/Remote/NetEaseMusic/controller/category.js (129)
[3882:0612/223438:ERROR:nw_shell.cc(335)] TypeError: Cannot read property 'appendChild' of undefined
    at file:///home/jqk/ProjectFiles/Remote/NetEaseMusic/controller/category.js:283:28
    at Array.forEach (native)
    at Object.Category.addtoDOM (file:///home/jqk/ProjectFiles/Remote/NetEaseMusic/controller/category.js:276:23)
    at Object.<anonymous> (file:///home/jqk/ProjectFiles/Remote/NetEaseMusic/controller/category.js:294:18)
    at file:///home/jqk/ProjectFiles/Remote/NetEaseMusic/controller/index.js:18:25
    at m.event.dispatch (file:///home/jqk/ProjectFiles/Remote/NetEaseMusic/assets/js/jquery.min.js:3:8553)
    at r.handle (file:///home/jqk/ProjectFiles/Remote/NetEaseMusic/assets/js/jquery.min.js:3:5263)
    at Object.m.event.trigger (file:///home/jqk/ProjectFiles/Remote/NetEaseMusic/assets/js/jquery.min.js:3:7654)
    at m.fn.extend.triggerHandler (file:///home/jqk/ProjectFiles/Remote/NetEaseMusic/assets/js/jquery.min.js:3:15602)
    at Object.Event.emit (file:///home/jqk/ProjectFiles/Remote/NetEaseMusic/controller/index.js:27:15)
[3882:0612/223438:INFO:CONSOLE(283)] "Uncaught TypeError: Cannot read property 'appendChild' of undefined", source: file:///home/jqk/ProjectFiles/Remote/NetEaseMusic/controller/category.js (283)

**Comment by stkevintan** [comment]
尝试删除data目录重启试试

**Comment by 910JQK** [comment]
搞定
